version: "3.8"

services:
  integration-test:
    image: cypress/included:8.1.0
    entrypoint: cypress
    command: run --browser chrome
    working_dir: /e2e
    volumes:
      - ./js/demo-apps/packages/react-front-end:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    depends_on:
      - localstack
      - proxy
      - cdk-init
      - secure-frame-iframe
      - customer-front-end
      - customer-back-end
      - secureframe
    environment:
      - DISPLAY=${DISPLAY}
