version: "3.8"

services:
  integration-test:
    build:
      context: .
      dockerfile: js/docker/demo.dockerfile
      target: integration-test
    entrypoint: npm run test:e2e
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /videos:/repo/js/demo-apps/packages/react-front-end/cypress/videos
    network_mode: host
    depends_on:
      secure-frame-iframe:
        condition: service_healthy
      application-front-end:
        condition: service_healthy
      application-back-end:
        condition: service_healthy
      tokenizerbackend:
        condition: service_healthy
# Uncomment to open the cypress UI locally
#    environment:
#      - DISPLAY=${DISPLAY}
