header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: by LunaSec (owned by Refinery Labs, Inc)
  paths:
    - '.github/**'
    - 'js/**/*.{js,jsx,ts,tsx}'
    - 'go/**/*.go'
    - 'lunatrace/cli/**/*.go'
    - 'lunatrace/tools/**/*.go'
    - 'api-spec/**/*.yaml'
  paths-ignore:
    - '.git'
    - '.idea'
    - '.idea/*'
    - '.idea/**'
    - 'licenses'
    - 'docs'
    - 'docs/**'
    - '**/dist/**'
    - 'js/**/build/**'
    - 'lunadefend/js/sdks/packages/secure-frame-iframe/public/**'
    - 'lunadefend/js/sdks/packages/tokenizer-sdk/src/generated/**'
    - 'lunadefend/js/sdks/packages/cli/src/cli.ts'
    - 'go/build/**'
    - '**/node_modules/**'
  comment: on-failure
  license-location-threshold: 3000
