version: '3.6'
services:
  oathkeeper:
    build:
      context: ./ory/oathkeeper
      args:
        OATHKEEPER_HASURA_URL: "http://graphql-engine:8080"
        OATHKEEPER_FRONTEND_URL: "http://host.docker.internal:3000"
        OATHKEEPER_BACKEND_URL: "http://host.docker.internal:3002"
        OATHKEEPER_KRATOS_URL: "http://kratos:4433"
        OATHKEEPER_MATCH_URL: "<https|http|ws>://localhost:4455"
    image: lunatrace-oathkeeper
    ports:
      - "4455:4455" # public
      - "4456:4456" # admin
    command: '--config /generated/config.yaml serve'
    environment:
      ACCESS_RULES_REPOSITORIES: file:///generated/rules.yaml
      MUTATORS_ID_TOKEN_CONFIG_JWKS_URL: file:///config/jwks.dev.json
      OATHKEEPER_HASURA_URL: "http://graphql-engine:8080"
      OATHKEEPER_FRONTEND_URL: "http://host.docker.internal:3000"
      OATHKEEPER_BACKEND_URL: "http://host.docker.internal:3002"
      OATHKEEPER_KRATOS_URL: "http://kratos:4433"
      OATHKEEPER_MATCH_URL: "<https|http|ws>://localhost:4455"
    volumes:
      - "./ory/oathkeeper:/config"
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:4455/health/ready || exit 1']
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kratos-migrate:
    build: ./ory/kratos
    image: lunatrace-kratos:lunatrace-dev
    depends_on:
      - postgres
    environment:
      DSN: postgres://postgres:postgrespassword@postgres:5432/lunatrace
    volumes:
      - ./ory/kratos:/config
    command: -c /config/config.yaml migrate sql -e --yes
    restart: on-failure

  kratos:
    build: ./ory/kratos
    image: lunatrace-kratos
    depends_on:
      - postgres
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      DSN: postgres://postgres:postgrespassword@postgres:5432/lunatrace
      LOG_LEVEL: trace
      KRATOS_ADMIN_URL: http://localhost:4434
    command: serve -c /config/config.yaml -c /config/config.dev.yaml --dev --watch-courier
    volumes:
      - ./ory/kratos:/config
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:4434/health/ready || exit 1']
    extra_hosts:
    - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:12
    restart: always
    # Uncomment this if you want Postgres to log queries out.
    # command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/tmp", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    ports:
      - "5431:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: lunatrace

  graphql-engine:
    image: hasura/graphql-engine:v2.9.0.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
      - postgres
      - oathkeeper
    restart: always
    volumes:
      - ./hasura:/hasura
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/lunatrace
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/lunatrace
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "false"
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "http://oathkeeper:4456/.well-known/jwks.json", "issuer": "http://oathkeeper:4455/"}'
      HASURA_GRAPHQL_LOG_LEVEL: debug
      ACTION_BASE_URL: http://host.docker.internal:3002
      # TODO: ADD THIS TO THE CDK
      REMOTE_SCHEMA_URL: http://host.docker.internal:3002/graphql/v1
      # COMMENT OUT THESE DIRs IF HASURA WONT START DUE TO MIGRATION OR METADATA ISSUES
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  We need better namespacing in datadog before we enable this again.
#  Currently, it will log alongside production which gets quite noisy.
#  datadog:
#    image: datadog/agent:latest
#    environment:
#     DD_LOGS_ENABLED: "true"
#     DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
#     DD_CONTAINER_EXCLUDE_LOGS: "name:datadog-agent"
#    env_file:
#      - .env.dev
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "/proc/:/host/proc/:ro"
#      - "/opt/datadog-agent/run:/opt/datadog-agent/run:rw"
#      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
#      - "./backend/logs/:/logs/:rw"
#      - "./datadog/:/etc/datadog-agent/conf.d/lunatrace.d/:ro"

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
volumes:
  db_data:

