version: v0.9.0-alpha.3
serve:
  public:
    base_url: https://lunatrace.lunasec.io/api/kratos/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: https://lunatrace.lunasec.io/
  allowed_return_urls:
    - https://lunatrace.lunasec.io

  flows:
    error:
      ui_url: https://lunatrace.lunasec.io/auth/error

    settings:
      ui_url: https://lunatrace.lunasec.io/api/kratos/settings

    recovery:
      ui_url: https://lunatrace.lunasec.io/api/kratos/recovery

    verification:
      ui_url: https://lunatrace.lunasec.io/api/kratos/verification
      after:
        default_browser_return_url: https://lunatrace.lunasec.io/

    logout:
      after:
        default_browser_return_url: https://lunatrace.lunasec.io

    login:
      ui_url: https://lunatrace.lunasec.io
      lifespan: 10m
      after:
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://localhost:3002/github/login
                method: POST
                body: file:///config/oidc.hook.jsonnet

    registration:
      ui_url: https://lunatrace.lunasec.io/
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            # Please preserve this slack hook in position [0] of this array, we are referencing it with an env var to load the secret
            - hook: web_hook
              config:
                url: http://fake-slack-url-replaced-by-env-var-in-prod.com
                method: POST
                body: file:///config/slack.hook.jsonnet
                response:
                  ignore: true
            - hook: session
            - hook: web_hook
              config:
                url: http://localhost:3002/github/login
                method: POST
                body: file:///config/oidc.hook.jsonnet




log:
  level: json
  format: text
  leak_sensitive_values: false

