lunasec:
  customer_front_end: http://localhost:3000
  customer_back_end: http://localhost:3001
  localstack_url: http://localhost:4566
  cdn_config:
    main_script: js/main-dev.js
    main_style: main.css
  session_public_key: "MIIBCgKCAQEAln1mVmoIRjDGQ4pVccsB5yJ3DFItUe9zLFU4naqsfFYJywKyAsH48wUHkBX0ZRurnEEomtxmj3F9B+dZ+ULFe3JnFrWDjN7XOFxyn3JfXjwVfEfA2FxYLLxgwZxfFFvcWCh2jodAlPO66LBteSbApclvSnp74ZHCSEr8DFCv7LU50d0oH+xhrN1h6YLvLGLbdFFZpvw1drBaV7KNvOR8t4qMbcTdDj5fWPBmKZ5aY4e3pKX89SBc8CtYfBcfSM7u4kxdGIt+nka29SyKSYBxWLc4bFMKOwWjw0ge/LbnwtFElQ+RyTo7ASj+oNK3CRORNAaxY+Oz8qL00cuwuo3aPQIDAQAB"
  front_end_assets_folder: ../js/sdks/packages/secure-frame-iframe/public/
aws_gateway:
  region: us-west-2
  access_key_id: test
  secret_access_key: test
  localstack_url: http://localstack:4566
