name: LunaTrace Deploy Production

on:
  workflow_dispatch:

concurrency: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master # This is what gives the job access to the secret env vars
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: yarn install
        env:
          IS_LUNASEC_CI: true
        run: yarn install --immutable --inline-builds
      - name: deploy
        run: |-
          set -euox pipefail
          
          cd lunatrace/bsl/backend-cdk
          STACK_VERSION=V2 yarn run cdk:deploy:prod